manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ftc/
  projects:
    - name: zmk
      remote: zmk
      revision: zmk_split
      import: app/west.yml
  self:
    path: config